services:
  - type: web
    name: ipsco-fastapi
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false  # À configurer manuellement dans Render
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    autoDeploy: true
    healthCheckPath: /docs
